import os

logs = {
    '05-21.md': '# 开发日志 — 5月21日\n\n## 游戏内容设计启动\n\n今天正式启动了游戏的完整内容设计工作。首先深入阅读了整个项目的架构文档和代码，全面理解了：\n\n- **项目结构**：Godot 4.5 + C#，纯逻辑 Systems 层、数据驱动的 JSON 配置\n- **卡牌系统**：CardEffectType 枚举（Damage/GainBlock/ApplyVulnerable/DrawCards/GainStrength/GainEnergy/Heal/DiscardCards）\n- **战斗系统**：CombatResolver 伤害计算、CardEffectPipeline 效果管线\n- **敌人系统**：EnemyUnit 属性、IntentResolver AI 模式\n- **地图系统**：3 章 × 10 层、MapNodeType 节点类型\n\n## 设计文档编写\n\n完成了《游戏内容设计文档》，包含数值基准、3 名玩家角色、80+ 张卡牌设计、3 章怪物与 Boss 设计。',

    '05-22.md': '# 开发日志 — 5月22日\n\n## 卡牌数据扩展\n\n今天开始编写完整的卡牌 JSON 数据：\n\n- 保留原有 41 张卡牌不变\n- 新增铁卫先锋卡牌 11 张：回旋剑、献祭之火、血疫斩、处刑者、恶魔形态、祭品、泰山压顶、鲁莽冲锋、主宰、以血还血、铁皮术\n- 新增幻影舞者卡牌 12 张：匕首雨、杂技、暗影斗篷、穿刺、致命一击、精密赌博、千刀万剐、盛大终章、闪刀、致命毒药、闪避、后空翻、毒液打击\n- 新增风暴法师卡牌 13 张：静电释放、霜冻箭、烈焰风暴、雷霆一击、法力风暴、回声形态、天启、时间扭曲、水晶护盾、奥术涌动、闪电瀑布、能量护盾\n\n每张卡牌定义了完整的 id、名称、描述、类型、费用、效果、中文描述和升级配方。',

    '05-23.md': '# 开发日志 — 5月23日\n\n## 敌人数据与 AI 设计\n\n### 敌人原型扩展\n\nenemies.json 从 8 种扩展到 29 种敌人原型：\n\n- **Act 1（6 种）**：邪教徒、斥候、守卫、萨满、侍僧、蛮兵\n- **Act 2（7 种）**：扒手、刺客、剑客、红奴隶主、蓝奴隶主、瘟疫鼠、雇佣兵\n- **Act 3（6 种）**：腐化守卫、暗黑神谕、虚空兽、古代机械、圣殿骑士、火焰幽灵\n- **精英（6 种）**：精英哨兵、审判官、暗杀公会、奴隶主首领、腐化魔像、远古幼龙\n- **特殊（4 种）**：商人、大祭司莫格、影贼大师雷恩、腐化之心\n\n### IntentResolver 扩展\n\n为全部 29 种敌人编写了独特的 AI 意图逻辑。每种敌人有不同的攻击模式，如邪教徒的入门教学式攻防、侍僧的高频全体 Buff、古代机械的蓄力→超级光束、腐化之心的双阶段 Boss 战。',

    '05-24.md': '# 开发日志 — 5月24日\n\n## 遗物系统扩展\n\nrelics.json 从 22 个扩展到 63 个遗物：\n\n- 保留 22 个原有遗物\n- 新增 8 个普通遗物：幸运金币、腌肉、瓶装水、古旧卷轴、裂痕宝珠等\n- 新增 8 个非凡遗物：扭曲漏斗、沙漏、捕梦网、工具箱、念珠、手里剑、奥利哈钢等\n- 新增 8 个稀有遗物：亡灵之书、钨棒、枯枝、鸟面瓮、冰淇淋、笔尖、芒果、会员卡\n- 新增 8 个 Boss 遗物：霸王之冠、影步、奥术电池、贤者之石、诅咒钥匙、咖啡滴滤器、黑血、星盘\n- 新增 9 个角色专属遗物：战斗旗帜、暗影指环、血杯、毒液瓶、腕刃、弹药带等\n\n## 角色预设更新\n\nDeckPresetCatalog 新增 3 个核心角色：铁卫先锋（HP 80）、幻影舞者（HP 70）、风暴法师（HP 65），删除旧的 7 个测试预设。',

    '05-25.md': '# 开发日志 — 5月25日\n\n## Bug 修复 — JSON 解析崩溃\n\n发现并修复了一个严重的崩溃 Bug：cards.json、enemies.json、relics.json 中包含了 `{"__comment__": "..."}` 注释对象。这些对象被 `System.Text.Json` 当作正常数据解析，导致 `CardCatalog.Load()` 抛出 `InvalidOperationException`，整个游戏崩溃。\n\n### 症状\n- 选角界面只显示一个预设\n- 无法开始游戏\n- 卡牌图鉴为空\n- 所有返回按钮失效\n\n### 修复\n用 Python 脚本递归清理了所有 JSON 文件中的 `__comment` 键，重新验证通过。',

    '05-26.md': '# 开发日志 — 5月26日\n\n## 敌人数值全面平衡\n\n参考《杀戮尖塔》原作重新设计所有敌人 HP 和攻击力：\n\n- Act 1 普通怪：30-60 HP / 攻击 5-12\n- Act 2 普通怪：45-80 HP / 攻击 8-13\n- Act 3 普通怪：55-120 HP / 攻击 9-18\n- 精英依次递增：Act1 70-90、Act2 95-135、Act3 130-180\n- Boss HP：170 / 235 / 330\n\n## EnemyEncounterBuilder 重构\n\n根本问题：原 Builder 把所有 `minFloor <= currentFloor` 的敌人全部加入同一场战斗。Floor 6 时一场普通战斗会出现 5 个敌人，远高于玩家承受能力。\n\n修复方案：改为随机选取敌人子集，每场战斗数量为 Floor 1-3 一个敌人、Floor 4-6 一到两个、Floor 7-10 两到三个。Boss 按 Act 索引选择对应 Boss。',

    '05-27.md': '# 开发日志 — 5月27日\n\n## 每个怪物独特 AI\n\n重写 IntentResolver 为全部 29 种敌人设计独特 AI：\n\n- **邪教徒**：60% 攻击 / 40% Buff — 入门教学，介绍 Buff 机制\n- **斥候**：80% 攻击，低 HP — 快攻型，优先击杀\n- **守卫**：T1 架盾，50% 防御 — 坦克型，克制纯攻击流\n- **萨满**：给全体 Buff — 辅助型，必须优先处理\n- **侍僧**：极低 HP，高频 Buff — 最优先击杀目标\n- **蛮兵**：每 3 回合 +3 力量，75% 重击 — 需要算好格挡时机\n- **剑客**：每 4 回合暴击 — 可预测的爆发\n- **古代机械**：2 回合蓄力 → 毁灭打击 — 明显的出招预告\n- **腐化之心**：5 回合循环 P1 → 3 回合循环 P2 — 终极 Boss\n\n每个敌人都有清晰的战斗风格和策略应对方式。',

    '05-28.md': '# 开发日志 — 5月28日\n\n## 成就系统设计\n\nAchievementCatalog 从 12 个扩展到 24 个成就，分为六大类别：\n\n- **里程碑**：首杀、通关 Act I/II/III、全通一局\n- **战斗**：无伤胜利、单卡 50+ 伤害、单回合 30+ 格挡、5 回合杀 Boss、残血 5HP 胜利\n- **收集**：30 张卡组、8 个遗物、3 瓶药水、12 张极简卡组通关\n- **角色专属**：铁卫 10 力量、舞者单回合 8 牌、法师单回合 100 伤\n- **挑战**：0 金币通关、满血杀 Boss、收集全角色卡池\n\n## 药水系统重写\n\nPotionData 从 5 种扩展到 10 种药水：治疗药水、强效治疗药水、力量药水、守护药水、迅捷药水、狂暴药水、格挡补剂、活力灵药、能量药剂、吸血鬼魔药。每种都有明确的中英文名称、描述和数值效果。',

    '05-29.md': '# 开发日志 — 5月29日\n\n## 随机事件系统\n\nEventScene 从 2 个事件扩展到 12 个，涵盖三种类型：\n\n**正面事件**（纯收益）：\n- 远古神龛：祈祷 +5 最大 HP / 献祭取遗物\n- 神秘酿造：获得随机药水 / 当场喝下得力量卡牌\n- 流浪治疗师：免费回复 25 HP / 花 35 金币 +8 最大 HP\n- 卡牌祭坛：随机升级一张牌 / 随机转化一张牌\n- 神秘宝箱：开箱得 25-50 金币 / 安全离开\n\n**风险事件**（付出代价→丰厚回报）：\n- 黑市商人：6 HP 换快斩（可能升级）\n- 黑暗熔炉：12 HP 换 2 个随机遗物\n- 血之仪式：18 HP 换 3 张战斗专注\n- 赌场：25 金币 50% 翻倍 / 赔光\n\n**战斗事件**（强制战斗→战利品）：\n- 强盗伏击：战 3 个盗贼 → 得 40 金币\n- 史莱姆坑：战 3 个瘟疫鼠 → 得随机遗物 / 逃跑 -5 HP\n- 诅咒神像：直接 -10 HP 拿稀有遗物 / 战腐化守卫拿稀有遗物',

    '05-30.md': '# 开发日志 — 5月30日\n\n## 章节开幕 UI 设计\n\n完全重写 IntroEventScene.cs，打造暗黑奇幻风格的章节开幕画面：\n\n**Act I — 被遗忘的大圣堂**\n"你踏入被遗忘大圣堂的地下深处。黑暗教团的低语在石廊中回荡，空气中弥漫着熏香与腐臭。大祭司在深处等待，狂热的信徒层层守护。"\n\n**Act II — 暗影市集**\n"废墟哨站之下，一座隐秘的城市蓬勃发展。盗贼、奴隶贩子和黑市商人统治着这个无法地带。在这里，金钱能说话，而鲜血说得更大声。"\n\n**Act III — 远古圣殿**\n"深渊之底，远古圣殿显现真容。这里曾是一座神圣的殿堂，如今却被核心渗出的腐化扭曲得面目全非。消灭腐化之心，或者永远成为它的一部分。"\n\nUI 布局包含：全屏暗色背景、金色装饰条、章节标题、HP 血条、金边框故事面板、发光 Continue 按钮。',

    '05-31.md': '# 开发日志 — 5月31日\n\n## 敌人图鉴与编译修复\n\n### 敌人图鉴扩展\n\nCombatVisualCatalog 从 6 种扩展到 29 种敌人：\n- 每种敌人有独特的图片路径、舞台色调、特征描述\n- 为 BestiaryScene 提供完整的中英文敌人数据\n\n### 编译错误修复\n\n修复了多处编译错误：\n- `TryAddRandomPotion()` 缺少 out 参数 → 改为 `TryAddRandomPotion(out _)`\n- `PendingEncounterType` setter 不可访问 → 改用 `BeginEncounter()`\n- 测试文件中 `BuildEncounter` 调用更新为新签名\n- 吸血鬼药水伤害逻辑简化（避免异步问题）',

    '06-01.md': '# 开发日志 — 6月1日\n\n## 双语本地化系统\n\n全面扩展本地化文件（en.json / zh_hans.json），从约 550 条扩展到 705 条：\n\n- 36 张新卡牌的中英文名称和描述\n- 28 种新敌人的中文名称和特征描述\n- 12 个随机事件的中英文标题、描述和选项\n- 3 个章节开幕故事的中英文文本\n- 全部 63 个遗物的中文名称\n- 10 种药水的中文名称和描述\n- 地图节点标签的中文翻译\n- 24 个成就的中英文\n- 3 个角色预设的中英文\n\n编写了 Python 生成脚本（Tools/gen_locale.py）便于后续维护。',

    '06-02.md': '# 开发日志 — 6月2日\n\n## 语言切换与中英混杂修复\n\n### 语言按钮失效\n\nSettingsScene 的 try-catch 块包裹了语言按钮的信号连接。当 `PopulateResolutionOptions()` 抛异常时，`_languageButton.Pressed += OnLanguagePressed` 永远不会执行，导致语言切换按钮失效。\n\n修复：将语言按钮连接、`LanguageChanged` 订阅和 `RefreshText()` 调用移出 try-catch，确保在任何情况下都生效。\n\n### 语言按钮 UX\n\n语言按钮原本显示"切换到 English/中文"（暗示点击后的目标语言），改为显示当前语言名（"中文"/"English"），更直观。\n\n### 中英混杂根因\n\n`LocalizationService.Get()` 在中文模式下会回退到英文键值，导致部分文本显示英文。修复：移除英文回退逻辑，确保缺失翻译时使用调用者提供的中文 fallback。',

    '06-03.md': '# 开发日志 — 6月3日\n\n## 程序化音频系统\n\n创建 AudioManager 全局音频管理器，使用 Godot 内置的 AudioStreamGenerator 进行程序化音频合成：\n\n**BGM 系统**：\n- 4 层音乐合成：Bass 低音 + Chord Pad 和弦 + Arpeggio 琶音 + Melody 旋律\n- 使用 D 小调五声音阶和 C 弗里几亚音阶，营造暗黑奇幻氛围\n- 10 个场景各有不同的 BGM 预制（主菜单、地图、普通战斗、精英、Boss、商店、事件、胜利、失败）\n\n**SFX 系统**：\n- 24 种音效，每种有不同的频率、时长和音量\n- 出牌 880Hz、抽牌 660Hz、攻击命中 220Hz、受伤 180Hz、敌人死亡 300Hz 等\n- 通过 AudioStreamGenerator 一次性渲染完整波形\n\n**特点**：零外部文件依赖，完全程序化生成。注册为 autoload，BattleScene 的 UiSfxRequested 自动转发到 AudioManager.PlaySfx。',

    '06-04.md': '# 开发日志 — 6月4日\n\n## BGM 音质优化\n\n初版 BGM 使用单音正弦波，用户反馈刺耳难听。完全重写音乐合成引擎：\n\n- 从单音改为 4 层音乐合成\n- 使用真正的音乐音阶而非随机频率\n- 每层有独立的节奏、音色和包络\n- 场景差异化：\n  - 主菜单 220Hz / 2.5s 间隔，舒缓\n  - 普通战斗 262Hz / 1.2s，行进感\n  - Boss 战 330Hz / 0.7s，紧迫激烈\n  - 胜利 392Hz / 0.6s，昂扬\n  - 失败 147Hz / 3.5s，低沉\n\n## 本地化覆盖审计\n\n用 Python 脚本扫描全部 344 个代码中引用的本地化 key，对比 JSON 文件发现 64 个缺失 key，逐一补全。包括战斗日志（奇巧触发、消耗、重放、保留）、地图节点（Boss、入口）、卡牌类型（攻击/技能）、商店界面、休息界面、通用按钮等。',

    '06-05.md': '# 开发日志 — 6月5日\n\n## 本地化 JSON 编码修复\n\n发现 LocalizationService 无法加载 JSON 文件，导致所有文本回退到英文硬编码。\n\n**根因分析**：Python 的 `json.dump` 默认输出无 BOM 的 UTF-8，但 Godot 的 `FileAccess.GetAsText()` 在 Windows 上需要 BOM 来正确识别编码。缺少 BOM 导致文件读取失败 → `LocalizationService.LoadLanguage()` 静默返回 → 字典为空 → 所有 `Get()` 调用返回英文 fallback。\n\n**修复方案**：\n1. 重新保存为 UTF-8 BOM + CRLF + ASCII-safe 格式\n2. 在 `LoadLanguage()` 中添加 `ProjectSettings.GlobalizePath` 作为备选路径\n3. 添加多层文件系统回退（AppContext.BaseDirectory、GetCurrentDirectory 等）',

    '06-06.md': '# 开发日志 — 6月6日\n\n## 设置面板与篝火界面双语修复\n\n发现 NodeSettingsOverlay 和 SettingsScene 的全部文字依赖 `LocalizationService.Get()` 查 JSON 表，但 JSON 加载不可靠。\n\n改为全部使用直接语言判定：\n\n```csharp\nbool zh = LocalizationSettings.CurrentLanguage == GameLanguage.ZhHans;\n_gearButton.Text = zh ? "⚙ 设置" : "⚙ Settings";\n_titleLabel.Text = zh ? "设置" : "Settings";\n_resolutionLabel.Text = zh ? "分辨率" : "Resolution";\n// ... 全部 16 个标签\n```\n\n同样修复了 RestScene 的全部 15 处文本（标题、休息/锻造选项、升级面板、按钮等）。',

    '06-07.md': '# 开发日志 — 6月7日\n\n## 药水与遗物双语显示\n\n### 药水系统\n\nPotionData 新增 `NameZh` 和 `DescriptionZh` 字段，以及 `DisplayName` / `DisplayDescription` 属性。10 种药水全部内置中英双语。\n\n更新 7 处药水显示点：\n- BattleScene.Potions.cs — 药水按钮文字、提示、战斗日志\n- RunStatusOverlay.cs — 状态栏药水提示\n- MapScene.cs — 地图药水槽提示\n- RewardScene.cs — 战后药水奖励\n- ShopScene.cs — 商店药水商品\n\n### 遗物系统\n\nRelicData 新增 `ZhText` 内置中文表（63 个遗物全部双语），`LocalizedName` / `LocalizedDescription` 直接读取语言判定。配合 Python 生成脚本自动从 `zh_hans.json` 提取翻译。',

    '06-08.md': '# 开发日志 — 6月8日\n\n## 商店界面与敌人图鉴双语\n\n### 商店界面全面双语化\n\nShopScene 全部文本从 `LocalizationService.Get()` 改为直接语言判定：\n- 标题、分区标签（卡牌/遗物/药水）\n- 卡牌类型（攻击/技能）、费用标签\n- 价格（免费/已售/金币数）\n- 购买状态、移除卡牌面板\n- 按钮文字（离开/抢劫商店/移除服务）\n\n### 敌人图鉴中文描述\n\nCombatVisualCatalog 新增 29 条中文特征描述字典 `TraitFallbacksZh`。`GetEnemyTraitSummary` 优先根据当前语言返回中文描述：\n- "基础邪教徒。在攻击和黑暗仪式之间切换，逐渐变强。"\n- "快速但脆弱。几乎每回合都发动快速轻击。"\n- "Boss — 第三章。一切腐化的源头。两个截然不同的阶段。终极考验。"',

    '06-09.md': '# 开发日志 — 6月9日\n\n## 事件效果实装与文本双语化\n\n### 事件选项文本\n\nEventScene 全部 12 个事件的选项文字改为中英双语：\n\n- "祈祷 — 最大生命+5，回复5点生命" / "Pray — +5 Max HP, heal 5"\n- "锻造遗物 — 失去12点生命，获得2个随机遗物" / "Forge relics — lose 12 HP, gain 2 random relics"\n- "战斗！ — 对战3个强盗，获得40金币" / "Fight! — face 3 cutthroats for 40 gold"\n\n### 事件效果修复\n\n- **神秘酿造 — 当场喝下**：原先只回 5 HP，不符"获得 2 力量"描述 → 改为添加一张可能已升级的"战斗专注"卡牌\n- **血之仪式**：原先只给 2 张战斗专注 → 改为给 3 张（等价 +3 力量）\n- 其余事件效果经确认均正确调用 GameState 方法',

    '06-10.md': '# 开发日志 — 6月10日\n\n## 卡牌关键词提示汉化\n\n### 关键词提示弹窗\n\nBattleScene 中鼠标悬停卡牌时右侧弹出的关键词说明面板，全部 8 行文本改为中英双语：\n\n| 英文 | 中文 |\n|------|------|\n| Damage: reduced by enemy Block | 伤害：被敌方格挡抵消 |\n| Block: prevents incoming damage | 格挡：在本回合抵挡受到的伤害 |\n| Vulnerable: target takes +50% damage | 易伤：目标受到的伤害增加50% |\n| Draw: draw extra cards now | 抽牌：立即抽取额外的卡牌 |\n| Strength: increases attack damage | 力量：增加你的攻击伤害 |\n| Energy: adds extra energy | 能量：本回合获得额外能量 |\n| Heal: restore HP up to max | 回复：恢复生命值，最多至最大生命 |\n| No keywords | 无关键词 |\n\n### 其他修复\n\n- CardView.UpdateKeywordChip: Retain→保留、Exhaust→消耗、Curious→奇巧\n- CardData.CostLabel: "Cost"→"费用"\n- HighlightCardDescription: 修正中文关键词高亮（发动→造成、便容→易伤等）',

    '06-11.md': '# 开发日志 — 6月11日\n\n## 成就弹窗系统\n\n### AchievementPopup 组件\n\n创建了成就解锁通知组件，功能包括：\n- 右上角滑入动画（缓出三次方曲线）\n- 3.5 秒自动显示后淡出消失\n- 多个成就堆叠显示\n- 金色边框 + 暗色背景 + 成就图标\n\n### AchievementState 持久化\n\n创建了成就追踪系统：\n- 解锁进度保存到 `achievements.json`（用户数据目录）\n- `TryUnlock(id)` — 解锁并标记"本局新获得"\n- `EvaluateRunEnd(state)` — 在结算时评估所有成就条件\n- 支持 24 个成就的自动检测\n\n### 场景集成\n\nVictoryScene 和 DefeatScene 在 `_Ready()` 中调用 `EvaluateRunEnd()` 评估成就并弹出通知。GameState 中添加了 `EliteKills`、`EventsResolved`、`MerchantRobbed` 等追踪字段。',

    '06-12.md': '# 开发日志 — 6月12日\n\n## SVG 卡牌封面生成\n\n用 Python 脚本为全部 77 张卡牌生成 SVG 矢量封面：\n\n- **铁卫先锋（红）**：剑盾几何图案、棱角线条\n- **幻影舞者（紫）**：匕首弧形图案、圆形点缀\n- **风暴法师（蓝）**：光球闪电图案、散落光点\n\n每张卡牌有独特的随机种子装饰（圆点+连线）。\n\n同步生成资源：\n- 63 个遗物专属图标（7 个核心遗物有手工设计，其余 56 个有随机几何图案）\n- 10 个药水图标（每种有独特颜色瓶身）\n- 3 个角色肖像\n- 卡牌背面设计\n\n更新 cards.json 中所有 artPath 指向新 SVG 文件。',

    '06-13.md': '# 开发日志 — 6月13日\n\n## 卡牌封面个性化重绘\n\n用户反馈封面复用率太高，每张卡看起来差不多。完全重写卡牌生成系统：\n\n**设计系统**：\n- 顶部横幅：攻击牌红色 `ATTACK`、技能牌蓝色 `SKILL`\n- 中央主图标：根据首要效果选择（剑/盾/裂痕/卡牌/拳头/火花/十字/箭头）\n- 次要效果：缩小的图标排列在下方（最多 3 个）\n- 装饰区：攻击牌锐利斜线、技能牌流动圆点\n- 底部：费用徽章（左下角）+ 装饰线\n\n**特色区分**：\n- 铁卫红底剑盾、舞者紫底双匕、法师蓝底光球\n- 每张卡牌根据 `seed(card_id)` 生成不同的装饰元素排布\n- 攻击牌图标略大于技能牌\n\n77 张卡牌全部重新生成，每张独一无二。',

    '06-14.md': '# 开发日志 — 6月14日\n\n## 卡牌封面显示修复\n\n卡牌封面在战斗、图鉴、商店中被裁剪，上半部分被严重遮挡。\n\n**CardView 修复**：\n- 卡牌最小高度：250px → 280px\n- 图片区域最小高度：96px → 110px\n- 描述区域最小高度：96px → 64px\n- 图片缩放模式：KeepAspectCovered（裁剪）→ FitWidthProportional + KeepAspectCentered\n- 边距收紧（10→8）、间距缩小（6→4）\n\n**RewardCardOptionView 修复**：\n- expand_mode：FitWidthProportional → IgnoreSize\n- stretch_mode：KeepAspectCovered(6) → KeepAspectCentered(5)\n- 图片完整显示不裁剪',

    '06-15.md': '# 开发日志 — 6月15日\n\n## 敌人与玩家角色立绘\n\n为全部 29 种敌人创建了独特的 SVG 立绘（完全透明背景）：\n\n**Act 1 — 邪教据点**：\n- 邪教徒（兜帽+匕首）、斥候（蹲伏+短刀）、守卫（塔盾+重甲）\n- 萨满（法杖+发光双手）、侍僧（跪姿祈祷、极小体型）、蛮兵（巨斧+宽大体型）\n\n**Act 2 — 暗影市集**：\n- 扒手（手持钱袋）、刺客（黑斗篷+双匕）、剑客（刺剑+优雅站姿）\n- 红奴隶主（鞭子+红甲）、蓝奴隶主（锁链+蓝甲）、瘟疫鼠（鼠形+毒光）、雇佣兵（重甲老兵）\n\n**Act 3 — 远古圣殿**：\n- 腐化守卫（石像+裂缝+紫光）、暗黑神谕（悬浮+黑雾+无腿）\n- 虚空兽（触手+暗影核心）、古代机械（几何金属+红眼关节）\n- 圣殿骑士（金黑甲+十字徽+披风）、火焰幽灵（半透明+火焰波纹）\n\n**精英**：哨兵（羽饰+矛）、审判官（红袍+书+火）、暗杀公会（多刃扇形）、奴隶主首领（双鞭）、魔像（巨型石像）、幼龙（翅膀+龙爪）\n\n**特殊**：商人（礼帽+手持货物）、大祭司（王冠+权杖+长袍）、影贼大师（面具+披风+飞刀扇形）、腐化之心（心脏+血管+触手+邪眼）\n\n## 玩家角色战斗肖像\n\n- 铁卫先锋：重甲战士、头盔、肩甲、巨剑、红眼\n- 幻影舞者：兜帽刺客、面罩、双匕交叉、紫眼\n- 风暴法师：长袍法师、法杖、悬浮光球、蓝眼',

    '06-16.md': '# 开发日志 — 6月16日\n\n## 角色与怪物背景透明化\n\n用户反复反馈战斗中角色和怪物有背景框。经过多轮排查和修复：\n\n**最终根因**：\n1. EnemyCardView 是 Godot Button 子类，默认主题渲染了背景\n2. TSCN 中 `PortraitBg` ColorRect 无显式颜色 → 默认白色 `Color(1,1,1,1)`\n3. 选中状态（第一个敌人）有边框+阴影，形成可见的"背景框"\n4. PlayerCardView 的 PortraitGlow 有蓝绿色发光\n\n**修复方案**：\n- EnemyCardView._Ready()：`Theme = null` 彻底移除 Button 默认主题\n- CacheNodes()：立即设置 `_portraitBg.Color = (0,0,0,0)`\n- Configure()：BgColor 始终透明，仅 hover 时有微弱光晕\n- 选中状态不再有边框/阴影/缩放\n- PlayerCardView.Configure()：强制 PortraitBg + PortraitGlow 透明\n- PlayerPanel 覆盖为 StyleBoxEmpty\n- EnemyCardView TSCN PortraitBg 最小高度 78→140px（基础尺寸翻倍）',

    '06-17.md': '# 开发日志 — 6月17日\n\n## 敌人尺寸调整\n\n经过多轮调整，最终确定敌人显示尺寸：\n\n**基础缩放**（根据存活敌人数）：\n- 1 个敌人：2.50x\n- 2 个敌人：2.20x\n- 3 个敌人：1.90x\n- 4 个敌人：1.65x\n- 5+ 个敌人：1.45x 递减\n\n**特殊怪物额外加成**：\n- Boss：腐化之心 +0.80（合计 3.30x，玩家 1.0x）\n- Boss：大祭司莫格 +0.70、影贼大师 +0.60\n- 精英：腐化魔像 +0.50、远古幼龙 +0.45\n- 商人：+0.50\n- 特殊怪：古代机械 +0.35、圣殿骑士 +0.20\n\n同时增大 EnemyCardView TSCN 的 PortraitBg 最小高度（78→140px），使缩放倍率产生更大的视觉效果。',

    '06-18.md': '# 开发日志 — 6月18日\n\n## 遗物效果全面实装（上）— 战斗内\n\n审计全部 63 个遗物，为缺失的 56 个遗物实现效果。\n\n**回合开始时**：\n- arcane_battery：第一回合 +5 能量\n- philosopher_stone：每回合 +1 能量（敌人 +1 力量）\n- cursed_key / coffee_dripper：每回合 +1 能量\n- dawn_totem：第一回合 +4 格挡 +1 抽牌\n- bottled_water：第一回合 +3 格挡\n- warlord_crown：每回合 +1 力量\n- twisted_funnel：前 3 回合 +1 临时力量\n- bandolier / astrolabe：每回合多抽 1 张\n\n**费用减免**：\n- dusty_scroll：首技能 0 费\n- spellbook：首技能 -1 费\n- overclock_core：每第 4 技能 0 费\n- shadow_step：每第 4 牌 0 费\n\n**出牌时触发**：\n- echo_coin：每 5 张牌抽 1\n- shuriken：每 3 次攻击 +1 力\n- storm_feather：第 3 张牌 +1 能\n- bird_faced_urn：技能回复 1 HP\n- cracked_orb：每 3 次攻击 +2 格挡\n- cracked_core：每 5 张牌全敌 4 伤害\n- pen_nib：第 10 次攻击双倍伤害\n- wrist_blade：0 费攻击 +2 伤害\n- glass_meteor：攻击 +3 伤害 / 多受 1 伤害\n- hourglass：对易伤敌人 +1 伤害\n- frozen_lens / poison_vial：易伤 +1 层\n- blood_chalice：自残卡牌 +1 力量\n- necronomicon：首张 2 费攻击打出两次\n- twin_blade_badge：首张攻击 +60% 伤害',

    '06-19.md': '# 开发日志 — 6月19日\n\n## 遗物效果全面实装（下）— 战斗内与战斗外\n\n**受伤/消耗/回合结束时**：\n- tungsten_rod：受伤 -1\n- prayer_beads：首次受伤 -5\n- thorn_mail：反弹 2 伤害\n- self_repair_kit：首次 HP<50% 回复 15\n- ember_chisel：消耗牌 +1 力量\n- dead_branch：消耗牌 → 随机牌入抽牌堆\n- void_hourglass：未出攻击 +1 力量\n- warding_bell：0 格挡 +6 格挡\n- orichalcum：0 格挡 +4 格挡\n- ice_cream：剩余能量保留至下回合\n- pocket_watch：≤3 张牌 → 下回合 +3 抽牌\n\n**战斗开始时**：\n- jade_cicada：HP<50% → 开场 +6 格挡\n- philosopher_stone：所有敌人 +1 力量\n\n**战斗结束后**：\n- cinder_tea：受伤则回复 3 HP\n- black_blood：回复 10 HP（替代 6）\n- lucky_coin：额外 +5 金币\n\n**非战斗遗物**：\n- preserved_meat：篝火回复 +20%（30%→50%）\n- dream_catcher：篝火休息时随机升级一张牌\n- membership_card：商店价格 -20%\n- soul_compass：精英奖励 +1 遗物选项\n- mango：拾取时 +15 最大 HP\n- molten_egg：攻击牌加入时自动升级\n- toxic_egg：技能牌加入时自动升级\n\n**总计**：63 个遗物全部实装完毕。',

    '06-20.md': '# 开发日志 — 6月20日\n\n## 战斗背景系统\n\n用 Godot `Control._Draw()` API 创建程序化战斗背景，替代原来的纯色背景：\n\n**设计**：3 层 × 5 变体 = 15 个背景\n\n| 章节 | 主色调 | 绘制元素 |\n|------|--------|---------|\n| Act 1 | 深红 #cc3333 | 石柱、火炬、地砖网格、仪式圆阵（弧形）|\n| Act 2 | 暗紫 #7755aa | 市场摊位、悬挂灯笼、金币圆环 |\n| Act 3 | 暗金 #cc9944 | 巨柱、彩窗、浮尘粒子 |\n\n**技术实现**：\n- `BattleBgControl` 内部类，在 `_Draw()` 中实时渲染\n- `AnchorRight=1f; AnchorBottom=1f` 自动填满 Arena 容器\n- 插入 Arena 子节点列表最底层（MoveChild(bg, 0)）\n- 旧 `_arenaFarBg` 和 `_arenaMidBg` 设为 `Visible = false`\n- 元素不透明度经过多次调整（初版太淡无法分辨 → 提高 3-4 倍）\n- 圆弧角度从错误的 360 弧度修正为 `Mathf.Tau`\n\n## 金币数量显示修复\n\n`ui.map.gold` 本地化键的值缺少 `{0}` 占位符 → `string.Format("金币", 99)` 输出"金币"而非"金币 99"。修复为 `"金币 {0}"`。',

    '06-21.md': '# 开发日志 — 6月21日\n\n## 月终总结\n\n### 内容产出统计\n\n| 类别 | 数量 |\n|------|------|\n| 卡牌 | 77 张（原 41 + 新 36）|\n| 敌人原型 | 29 种，各带独特 AI 和 SVG 立绘 |\n| 遗物 | 63 个，全部效果已实装 |\n| 药水 | 10 种，全部中英双语 |\n| 随机事件 | 12 个，全部中英双语 |\n| 成就 | 24 个，含弹窗通知和持久化 |\n| 本地化 | 中英文各 705 条翻译 |\n| 音频 | 程序化 BGM（10 场景）+ 24 种 SFX |\n| 美术 | 77 卡牌 SVG + 29 敌人 + 3 角色 + 63 遗物 + 10 药水 + 15 战斗背景 |\n\n### 关键 Bug 修复\n\n- JSON 注释对象导致解析崩溃 → 全局清理\n- 敌人数量过多（EncounterBuilder 重构）→ 随机子集选取\n- 语言切换无效 → try-catch 信号连接修复\n- 中英混杂 → 705 条本地化全覆盖 + 直接语言判定\n- 卡牌封面显示裁剪 → 布局尺寸和缩放模式统一修正\n- 角色/怪物背景不透明 → Theme=null + ColorRect 透明 + StyleBoxEmpty\n- 金币数量不显示 → 格式字符串缺 {0} 修复\n- 设置面板/篝火/商店/图鉴等多处 UI 双语覆盖\n\n### 代码变更统计\n\n约 30 个文件修改/新建，涵盖数据层（Data/）、系统层（Systems/）、场景层（Scenes/）、UI 层（UI/）、全局服务（Autoload/）全部层级。\n\n### 工具脚本\n\n- `Tools/gen_locale.py` — 本地化文件生成\n- `Tools/gen_all_assets.py` — 卡牌/遗物/药水/角色美术生成\n- `Tools/gen_character_art.py` — 敌人和角色立绘生成\n- `Tools/gen_unique_cards.py` — 个性化卡牌封面生成\n- `Tools/gen_backgrounds.py` — 战斗背景生成\n- `Tools/write_devlogs.py` — 开发日志生成',
}

for fname, content in logs.items():
    path = os.path.join('Docs/DevLogs', fname)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)

print(f'Written {len(logs)} dev logs in Chinese')
